name: Execute tests on OCP
on:
  push:
    branches:
      - main
    tags:
      - 'v**'

env:
  GO_VERSION: "1.22"
  IMAGE_TAG_BASE: ghcr.io/${{ github.repository }}
  VERSION: "latest"

jobs:
  build-and-publish-operator:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set Version
        run: echo "VERSION=$(echo ${GITHUB_REF/refs\/tags\//})" >> $GITHUB_ENV
        if: ${{ github.ref_type == 'tag' }}
        
      - name: Checkout
        run: |
          echo "version:"
          echo $VERSION
        
